export default{
   splash_bg: require('../../Common/Public/Images/GradientBG.png'),
   welcome_bg: require('../../Common/Public/Images/1.2_WelcomeScreen2.png'),
   welcome_bg1: require('../../Common/Public/Images/12WelcomeScreen1.png'),
   welcome_bg3: require('../../Common/Public/Images/12WelcomeScreen3.png'),
   KandiSnap_Final_logo:require('../../Common/Public/Images/Kandisnap_Final_Logo.png'),
   signup_bg: require('../../Common/Public/Images/SignupBGPatetrn.png'),
   check: require('../../Common/Public/Images/CheckBox_Checked.png'),
   uncheck:require('../../Common/Public/Images/CheckBox_uncheck.png'),
   closeEye:require('../../Common/Public/Images/EyeClose.png'),
   openEye:require('../../Common/Public/Images/Eyeicon.png'),
   profile:require('../../Common/Public/Images/ProfileImage.png'),
   edit:require('../../Common/Public/Images/EditProfile.png'),
   gallery:require('../../Common/Public/Images/GalleryIcon.png'),
   HomeBG:require('../../Common/Public/Images/HomeBGPatetrn.png'),
   empty:require('../../Common/Public/Images/EmptyGraphic.png'),
   search:require('../../Common/Public/Images/Searchicon.png'),
   saved:require('../../Common/Public/Images/SavedKandis.png'),
   fb:require('../../Common/Public/Images/facebook.png'),
   detailBG:require('../../Common/Public/Images/DetailBGPatetrn.png'),
   like:require('../../Common/Public/Images/LikeIcon.png'),
   likeStats:require('../../Common/Public/Images/LikesStatsIcon.png'),
   camera:require('../../Common/Public/Images/CameraStatsIcon.png'),
   comment:require('../../Common/Public/Images/CommentStatsIcon.png'),
   creteKandi:require('../../Common/Public/Images/createKandiBG.png'),
   public:require('../../Common/Public/Images/Public_Icon.png'),
   private:require('../../Common/Public/Images/Private_Icon.png'),
   back:require('../../Common/Public/Images/BackIcon.png'),
   loc:require('../../Common/Public/Images/LocationIcon.png'),
   eventBG:require('../../Common/Public/Images/BGEvent.png'),
   offbg:require('../../Common/Public/Images/offlineBGPatetrn.png'),
   refresh:require('../../Common/Public/Images/Refreshicon.png'),
   bgOfflineHead:require('../../Common/Public/Images/BGOFFLINE.png'),
   DiscIconEn:require('../../Common/Public/Images/Discover_icon_Enable.png'),
   DiscIconDis:require('../../Common/Public/Images/Discover_icon_Disable.png'),
   NotIcon:require('../../Common/Public/Images/Notification_icon_Enable.png'),
   NotIconDis:require('../../Common/Public/Images/Notification_icon_Disable.png'),
   homeIconEn:require('../../Common/Public/Images/Home_icon_Enable.png'),
   homeIconDis:require('../../Common/Public/Images/Home_icon_Disable.png'),
   scancon:require('../../Common/Public/Images/scanIcon.png'),
   profileEn:require('../../Common/Public/Images/Profile_icon_Enable.png'),
   profileDis:require('../../Common/Public/Images/Profile_icon_disable.png'),
   eventBg:require('../../Common/Public/Images/ProfileBG.png'),
   calander:require('../../Common/Public/Images/CalendarIcon.png'),
   cancel:require('../../Common/Public/Images/Cancel_Button.png'),
   scan:require('../../Common/Public/Images/Overlay.png'),
   
   
}